from typing import Any

constexpr: Any

float16: Any
float32: Any

def program_id(axis: int) -> Any: ...
def cdiv(left: Any, right: Any) -> Any: ...
def arange(start: int, end: Any) -> Any: ...
def zeros(shape: tuple[Any, ...], dtype: Any) -> Any: ...
def load(pointer: Any, *, mask: Any, other: float) -> Any: ...
def dot(left: Any, right: Any, accumulator: Any) -> Any: ...
def store(pointer: Any, value: Any, *, mask: Any) -> None: ...
